### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [3ygun/Shuffle7Stream#1]
Dear 3ygun,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of Gotham-Black.otf in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by 3ygun** [comment]
Hopefully resolved? Sorry about that and thanks for bringing it to my attention! Best part about the entire thing is that the font didn't even work for my project. :D

**Comment by 3ygun** [comment]
Now more so: https://github.com/3ygun/Shuffle7Stream/pull/2
Or do I need to follow this option? https://help.github.com/articles/remove-sensitive-data/

**Comment by fontpolice** [comment]
Thank you for your cooperation.
